# Generated by Django 5.1.3 on 2024-11-23 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rosa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id_impresora', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=20)),
                ('anio_lanzamiento', models.CharField(max_length=5)),
                ('volumen_construccion', models.CharField(max_length=20)),
                ('precio', models.CharField(max_length=20)),
                ('moneda', models.CharField(max_length=20)),
                ('url_imagen', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=20)),
            ],
            options={
                'db_table': 'impresoras',
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_registro',
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='app_rosa.cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_impresora',
            field=models.ForeignKey(db_column='id_impresora', on_delete=django.db.models.deletion.CASCADE, to='app_rosa.impresora'),
        ),
        migrations.DeleteModel(
            name='Impresora3D',
        ),
    ]
